Minor cleanups to OOD files

diff --git a/template/bin/auth b/template/bin/auth
--- a/template/bin/auth
+++ b/template/bin/auth
@@ -1,16 +1,16 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 # Confirm username is supplied
 if [[ $# -lt 1 ]]; then
-  echo "Usage: auth USERNAME"
-  exit 1
+    echo "Usage: auth USERNAME"
+    exit 1
 fi
 USERNAME="${1}"
 
 # Confirm password environment variable exists
 if [[ -z ${RSTUDIO_PASSWORD} ]]; then
-  echo "The environment variable RSTUDIO_PASSWORD is not set"
-  exit 1
+    echo "The environment variable RSTUDIO_PASSWORD is not set"
+    exit 1
 fi
 
 # Read in the password from user
@@ -18,9 +18,9 @@ read -s -p "Password: " PASSWORD
 echo ""
 
 if [[ ${USERNAME} == ${USER} && ${PASSWORD} == ${RSTUDIO_PASSWORD} ]]; then
-  echo "Successful authentication"
-  exit 0
+    echo "Successful authentication"
+    exit 0
 else
-  echo "Invalid authentication"
-  exit 1
+    echo "Invalid authentication"
+    exit 1
 fi
